# codeql database analyze ./database/ /Users/lsiddiqsunny/codeql-home/codeql-repo/java/ql/src/Advisory --format=csv --output="./Output/DistributedMiningNetwork/Advisory.csv"
codeql database analyze ./database/ /Users/lsiddiqsunny/codeql-home/codeql-repo/java/ql/src/Compatibility --format=csv --output="./Output/DistributedMiningNetwork/Compatibility.csv"
codeql database analyze ./database/ /Users/lsiddiqsunny/codeql-home/codeql-repo/java/ql/src/Architecture --format=csv --output="./Output/DistributedMiningNetwork/Architecture.csv"
codeql database analyze ./database/ /Users/lsiddiqsunny/codeql-home/codeql-repo/java/ql/src/Compatibility --format=csv --output="./Output/DistributedMiningNetwork/Compatibility.csv"
codeql database analyze ./database/ /Users/lsiddiqsunny/codeql-home/codeql-repo/java/ql/src/Complexity --format=csv --output="./Output/DistributedMiningNetwork/Complexity.csv"
codeql database analyze ./database/ /Users/lsiddiqsunny/codeql-home/codeql-repo/java/ql/src/DeadCode --format=csv --output="./Output/DistributedMiningNetwork/DeadCode.csv"
codeql database analyze ./database/ /Users/lsiddiqsunny/codeql-home/codeql-repo/java/ql/src/Diagnostics --format=csv --output="./Output/DistributedMiningNetwork/Diagnostics.csv"
codeql database analyze ./database/ "/Users/lsiddiqsunny/codeql-home/codeql-repo/java/ql/src/Language Abuse" --format=csv --output="./Output/DistributedMiningNetwork/Language_Abuse.csv"
codeql database analyze ./database/ "/Users/lsiddiqsunny/codeql-home/codeql-repo/java/ql/src/Metrics" --format=csv --output="./Output/DistributedMiningNetwork/Metrics.csv"
codeql database analyze ./database/ "/Users/lsiddiqsunny/codeql-home/codeql-repo/java/ql/src/Performance" --format=csv --output="./Output/DistributedMiningNetwork/Performance.csv"
codeql database analyze ./database/ "/Users/lsiddiqsunny/codeql-home/codeql-repo/java/ql/src/Violations of Best Practice" --format=csv --output="./Output/DistributedMiningNetwork/Violations_of_Best_Practice.csv"
codeql database analyze ./database/ "/Users/lsiddiqsunny/codeql-home/codeql-repo/java/ql/src/Telemetry" --format=csv --output="./Output/DistributedMiningNetwork/Telemetry.csv"
codeql database analyze ./database/ "/Users/lsiddiqsunny/codeql-home/codeql-repo/java/ql/src/Security" --format=csv --output="./Output/DistributedMiningNetwork/Security.csv"

